### PR TITLE
added maixduino board analog example and fixed setColor

### PR DESCRIPTION
**Pull request by vanvuongngo**

### CODE REVIEW

**Comment by bitsk** [comment]
Thanks for your PR.
there are some boards like maixduino board doesn't have color leds, so i think modify it is not a good idea.

**Comment by vanvuongngo** [comment]
> Thanks for your PR.
> there are some boards like maixduino board doesn't have color leds, so i think modify it is not a good idea.

Good point and I will add an example for a maixduino with only a LED_BUILTIN.

**Comment by vanvuongngo** [comment]
@btx000 please T&V again - I reverted the constants and added an example for maixduino boards with single led.

**Comment by bitsk** [comment]
Well done！

**Pull request merged**
